name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PI_HOST }}
          username: raspberrypi
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/raspberrypi/cat-gpt-discord

            git pull origin main

            /home/raspberrypi/cat-gpt-discord/venv/bin/pip3 install -r requirements.txt

            sudo systemctl restart cat-gpt
